[target.aarch64-unknown-linux-gnu.env]
BINDGEN_EXTRA_CLANG_ARGS = "-I/usr/aarch64-linux-gnu/include"

[target.aarch64-unknown-linux-musl.env]
BINDGEN_EXTRA_CLANG_ARGS="-I/usr/local/aarch64-linux-musl/include"